--- 
# executing linux commands

- hosts: 172.31.8.36
  become: yes
  tasks:
    - name: i want to execute linux commmand
      command: hostname -f 
      register: myfirstlinuxcommandresult

    - name: i want to display my first linux command result
      debug: 
        msg: "{{myfirstlinuxcommandresult}}"