--- 
# creating files and handling files

- hosts: 172.31.8.36
  become: yes
  tasks:
    
   # - name: i want to create a file
    #  file:
     #   path: /home/ubuntu/mytestfile
      #  state: touch


     - include_tasks: myfile.yml #including different playbooks at a time
     - name: copy static file inti asnsible node
       copy:
          src: mytestfile 
          des: /home/ubuntu/mystaticfiles
