--- 
- hosts: all 
  become: yes
  tasks: 
    - name: install webserver on ansible node side
      apt:
        name: apache2
        state: present
      when: ansible_os_family== "Debian"  
    - name: start webserver on ansible node side
      service:
        name: apache2
        state: started