--- 
- hosts: all 
  become: yes
  tasks: 
    - name: install webserver on ubuntu ansible node 
      apt:
        name: apache2
        state: present
      when: ansible_os_family== "Debian"  
    - name: start webserver on ubuntu ansible node 
      service:
        name: apache2
        state: started
      when: ansible_os_family== "Debian" 

    - name:  install webserver on redhat ansible node 
      apt:
        name: httpd
        state: present
      when: ansible_os_family== "RedHat"  
    - name: start webserver on redhat ansible node 
      service:
        name: httpd
        state: started
      when: ansible_os_family== "RedHat"
