---

- name: add tomcat admin user
  template:
   src: templates/mytomusers.j2
   dest: /opt/tomcat/conf/tomcat-users.xml
- name: change context file
  template:
   src: templates/mytomcontext.j2
   dest: /opt/tomcat/webapps/manager/META-INF/context.xml
- name: change host context file
  template: 
   src: templates/mytomhostcontext.j2
   dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml