---
# tasks file for tomrole

- include_tasks: myadduser.yml

- include_tasks: installjava.yml

- include_tasks: downloadtar.yml

- include_tasks: permission.yml

- include_tasks: configadminuser.yml

- include_tasks: tomservice.yml

- include_tasks: tomstart.yml

